- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: 2dda8367897e80bb27d0c52bcbc8759f8119dfe3
  hooks:
      - id: trailing-whitespace
- repo: http://git.apertron.net/cgit.cgi/hooks/
  sha: origin/experimental
  hooks:
      - id: yamlcheck